# Generated by Django 5.0.4 on 2024-06-30 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgroups",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="supply_room.class",
                verbose_name="Clase",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Estudiante"),
                    ("teacher", "Profesor"),
                    ("admin", "Administrador"),
                ],
                default="student",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="student_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
