# Generated by Django 5.0.4 on 2024-06-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("student", "Estudiante"), ("teacher", "Profesor")],
                default="student",
                max_length=200,
            ),
        ),
    ]
