# Generated by Django 5.0.4 on 2024-06-22 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0002_alter_users_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroups",
            name="student",
            field=models.ManyToManyField(
                related_name="group_student", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
