# Generated by Django 5.0.4 on 2024-06-25 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0003_classgroups_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgroups",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="classgroups",
            name="student",
            field=models.ManyToManyField(
                blank=True, related_name="group_student", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="group_student", to="supply_room.classgroups"
            ),
        ),
    ]
