# Generated by Django 5.0.4 on 2025-03-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0003_alter_itemorder_code_alter_itemorder_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
