# Generated by Django 5.0.4 on 2024-06-25 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0004_alter_classgroups_professor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgroups",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_professor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
