# Generated by Django 5.0.4 on 2025-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0004_item_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgroups",
            name="number",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Numero de Curso:"
            ),
        ),
        migrations.AlterField(
            model_name="classgroups",
            name="year",
            field=models.PositiveIntegerField(default=2025, verbose_name="Año"),
        ),
    ]
