# Generated by Django 5.0.4 on 2024-06-25 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0005_alter_classgroups_professor"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="student",
            field=models.ManyToManyField(
                blank=True, related_name="Order_student", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="orders",
            field=models.ManyToManyField(
                blank=True, related_name="order_student", to="supply_room.order"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_group",
                to="supply_room.classgroups",
            ),
        ),
    ]
