# Generated by Django 5.0.4 on 2025-04-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0005_alter_classgroups_number_alter_classgroups_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userorder",
            options={
                "verbose_name": "Relación Usuario-Orden",
                "verbose_name_plural": "Relaciones Usuario-Orden",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="student",
        ),
        migrations.AlterUniqueTogether(
            name="userorder",
            unique_together={("user", "order")},
        ),
    ]
