# Generated by Django 5.0.4 on 2025-05-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0006_alter_userorder_options_remove_order_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classgroups",
            name="student",
        ),
    ]
