# Generated by Django 5.0.4 on 2024-06-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0006_order_student_users_orders_alter_order_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(
                blank=True, related_name="Order_item", to="supply_room.item"
            ),
        ),
    ]
