# Generated by Django 5.0.4 on 2024-06-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0007_order_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="item",
        ),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(
                blank=True,
                related_name="Order_item",
                through="supply_room.ItemOrder",
                to="supply_room.item",
            ),
        ),
    ]
