# Generated by Django 5.0.4 on 2025-05-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0007_remove_classgroups_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemorder",
            name="request_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de solicitud"
            ),
        ),
        migrations.AddField(
            model_name="itemorder",
            name="return_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de devolución"
            ),
        ),
    ]
