# Generated by Django 5.0.4 on 2025-05-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0008_itemorder_request_date_itemorder_return_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="code",
            field=models.CharField(blank=True, max_length=200, verbose_name="Código"),
        ),
    ]
