# Generated by Django 5.0.4 on 2024-06-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0009_remove_order_item_alter_itemorder_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                blank=True,
                related_name="Order_item",
                through="supply_room.ItemOrder",
                to="supply_room.item",
            ),
        ),
    ]
