# Generated by Django 5.0.4 on 2025-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0009_item_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemorder",
            name="loan_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de préstamo"
            ),
        ),
    ]
