# Generated by Django 5.0.4 on 2024-06-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0010_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
    ]
