# Generated by Django 5.0.4 on 2025-06-10 20:05

import supply_room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_room", "0010_itemorder_loan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classgroups",
            name="year",
            field=models.PositiveIntegerField(
                default=supply_room.models.get_current_year, verbose_name="Año"
            ),
        ),
    ]
